FROM node:22.17.0-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm run build

FROM node:22.17.0-alpine

WORKDIR /app

COPY --from=build /app ./

ENV NODE_ENV=production
EXPOSE 3117

CMD ["npm", "start"]
