import type { Metadata } from "next";
import "@fontsource/inter/index.css";
import "./globals.css";
import ReactQueryProvider from "@/providers/react-query.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body
          className="font-sans antialiased bg-background text-foreground min-h-screen"
        >
          {children}
        </body>
      </ReactQueryProvider>
    </html>
  );
}
