FROM elixir:1.17-alpine

RUN apk add --no-cache build-base git postgresql-dev nodejs npm bash postgresql-client

RUN elixir --version
RUN erl -version

WORKDIR /app

ENV MIX_ENV=prod
RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock ./
RUN mix deps.get --only prod

COPY . .
RUN mix compile

RUN npm install -g npm@11.6.2
RUN node --version && npm --version

RUN mix phx.digest

RUN mix release

COPY docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["_build/prod/rel/your_app/bin/your_app", "start"]
