FROM elixir:1.17-alpine

RUN apk add --no-cache build-base git postgresql-dev nodejs npm postgresql-client

WORKDIR /app

ENV MIX_ENV=prod

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock ./
RUN mix deps.get --only prod

COPY . .
RUN mix compile

RUN npm install -g npm@11.6.2
RUN mix phx.digest

RUN echo '#!/bin/sh\n\
  until pg_isready -h db -p 5432 -U $POSTGRES_USER; do\n\
  echo "Waiting for database..."\n\
  sleep 2\n\
  done\n\
  echo "Database is ready!"\n\
  mix ecto.migrate\n\
  mix phx.server' > /app/start.sh && chmod +x /app/start.sh

CMD ["/app/start.sh"]
